//---------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs" company="Microsoft">
//      Copyright (C) Microsoft Corporation. All rights reserved. See License.txt in the project root for license information.
// </copyright>
//---------------------------------------------------------------------

// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the
// Error List, point to "Suppress Message(s)", and click
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

#region Permanent Exclusions

#region Excluding autogenerated code

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ODataToolkit.Error.#NotSupported()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ODataToolkit.Error.#NotImplemented()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ODataToolkit.Error.#ArgumentOutOfRange(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ODataToolkit.Error.#ArgumentNull(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ODataToolkit.EntityRes.#Resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ODataToolkit.EntityRes.#GetString(System.String,System.Boolean&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ODataToolkit.EntityRes.#GetObject(System.String)")]

#endregion

#region Architectural Complaints
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "ODataToolkit.ToTraceStringExtensionMethods.#ToTraceString(ODataToolkit.IEdmSchemaType)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "ODataToolkit.EdmTypeSemantics.#InheritsFrom(ODataToolkit.IEdmStructuredType,ODataToolkit.IEdmStructuredType)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "ODataToolkit.EdmElementComparer.#IsEquivalentTo(ODataToolkit.IEdmAssociation,ODataToolkit.IEdmAssociation)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "ODataToolkit.ExtensionMethods.#DeclaringEntityType(ODataToolkit.IEdmNavigationProperty)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "ODataToolkit.ExtensionMethods.#ToEntityType(ODataToolkit.IEdmNavigationProperty)")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "ODataToolkit.IEdmCollectionTypeReference")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "ODataToolkit.IEdmEntityReferenceTypeReference")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "ODataToolkit.IEdmPrimitiveTypeReference")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "ODataToolkit.IEdmStructuredTypeReference")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "ODataToolkit.Vocabularies.IEdmVocabularyAnnotatable")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "ODataToolkit.Vocabularies.IEdmBinaryValue.#Value")]

#endregion

#region Naming Complaints

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "ODataToolkit.EdmConstants.#EdmVersion1_1", Justification = "Underscore is used instead of . in the version name. Can't replace it with anything better.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "ODataToolkit.EdmConstants.#EdmVersion1_2", Justification = "Underscore is used instead of . in the version name. Can't replace it with anything better.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "ODataToolkit.EdmConstants.#EdmVersion2_2", Justification = "Underscore is used instead of . in the version name. Can't replace it with anything better.")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "ODataToolkit.IEdmOperationImport.#IsComposable")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "IsComposable", Scope = "resource", Target = "ODataToolkit.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "composable", Scope = "resource", Target = "ODataToolkit.resources")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "MultiPoint", Scope = "member", Target = "ODataToolkit.EdmPrimitiveTypeKind.#GeometryMultiPoint")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "MultiLine", Scope = "member", Target = "ODataToolkit.EdmPrimitiveTypeKind.#GeographyMultiLineString")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "MultiPoint", Scope = "member", Target = "ODataToolkit.EdmPrimitiveTypeKind.#GeographyMultiPoint")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "MultiLine", Scope = "member", Target = "ODataToolkit.EdmPrimitiveTypeKind.#GeometryMultiLineString")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "To", Scope = "member", Target = "ODataToolkit.IEdmNavigationProperty.#To")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Property", Scope = "member", Target = "ODataToolkit.Vocabularies.IEdmPropertyValue.#Property")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Namespace", Scope = "member", Target = "ODataToolkit.IEdmSchemaElement.#Namespace")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Property", Scope = "member", Target = "ODataToolkit.Vocabularies.IEdmStructuredValue.#FindPropertyValue(ODataToolkit.IEdmProperty)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Property", Scope = "member", Target = "ODataToolkit.EdmStructuredType.#RemoveProperty(ODataToolkit.IEdmProperty)")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720:AvoidTypeNamesInParameters", MessageId = "1#", Scope = "member", Target = "ODataToolkit.Vocabularies.EdmToClrConverter.RegisterConvertedObject(ODataToolkit.Vocabularies.IEdmStructuredValue,System.Object):System.Void")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "ANon", Scope = "member", Target = "ODataToolkit.Validation.EdmErrorCode.#NullCannotBeAssertedToBeANonNullableType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "BeSide", Scope = "member", Target = "ODataToolkit.Validation.EdmErrorCode.#ComposableOperationImportCannotBeSideEffecting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "BeSide", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#OperationImportComposableOperationImportCannotBeSideEffecting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Srid", Scope = "member", Target = "ODataToolkit.Validation.EdmErrorCode.#InvalidSrid")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "ODataToolkit.Validation.ValidationRuleSet")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "ODataToolkit.Vocabularies.EdmDirectValueAnnotation.#.ctor(System.String,System.String,System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#", Scope = "member", Target = "ODataToolkit.Vocabularies.EdmDirectValueAnnotationBinding.#.ctor(ODataToolkit.IEdmElement,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#", Scope = "member", Target = "ODataToolkit.Vocabularies.EdmDirectValueAnnotationBinding.#.ctor(ODataToolkit.IEdmElement,System.String,System.String,System.Object)")]

#endregion

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ODataToolkit.EdmNamedElement.#elementName", Justification = "Making this a property would result in substantially worse code")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ODataToolkit.EdmStructuredType.#BaseStructuredType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "ODataToolkit.Vocabularies.EdmNullExpression.#Instance")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "ODataToolkit.EdmEntityType.#AddNavigation(System.String,ODataToolkit.EdmEntityType,ODataToolkit.EdmMultiplicity)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "ODataToolkit.EdmEntityType.#AddNavigation(System.String,ODataToolkit.EdmEntityType,ODataToolkit.EdmMultiplicity,ODataToolkit.EdmMultiplicity)")]

#endregion

#region Temporary Exclusions

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "ODataToolkit.Vocabularies.IEdmImmediateValueAnnotation.#NamespaceUri")]

#endregion
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "ODataToolkit.IEdmElement")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "ODataToolkit.Vocabularies.IEdmDirectValueAnnotation.#NamespaceUri")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "ODataToolkit.Vocabularies.IEdmDirectValueAnnotationBinding.#NamespaceUri")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "ODataToolkit.VersioningList`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "ODataToolkit.VersioningList`1+ArrayVersioningList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "ODataToolkit.VersioningList`1+EmptyVersioningList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "ODataToolkit.VersioningList`1+LinkedVersioningList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "ODataToolkit.VersioningDictionary`2")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "ODataToolkit.VersioningDictionary`2+EmptyVersioningDictionary")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "ODataToolkit.VersioningDictionary`2+HashTreeDictionary")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "ODataToolkit.VersioningDictionary`2+OneKeyDictionary")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "ODataToolkit.VersioningDictionary`2+TreeDictionary")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "ODataToolkit.VersioningDictionary`2+TwoKeyDictionary")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.VersioningDictionary`2.#CompareFunction")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.VersioningTree`2.#Key")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.VersioningTree`2.#LeftChild")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.VersioningTree`2.#RightChild")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.VersioningTree`2.#Value")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#DirectValueAnnotationHasXmlSerializableName")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#BinaryTypeReferenceBinaryUnboundedNotValidForMaxLength")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#OpenComplexTypeCannotHaveClosedDerivedComplexType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#DecimalTypeReferencePrecisionOutOfRange")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#EntityContainerDuplicateEntityContainerMemberName")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#EntityReferenceTypeInaccessibleEntityType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#EntitySetCanOnlyBeContainedByASingleNavigationProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationMappingMustBeBidirectional")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationPropertyMappingsMustBeUnique")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationSourceTypeHasNoKeys")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#EntityTypeEntityKeyMustBeScalar")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#EntityTypeInvalidKeyKeyDefinedInBaseClass")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#EntityTypeKeyMissingOnEntityType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#EnumMemberValueMustHaveSameTypeAsUnderlyingType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#EnumTypeEnumMemberNameAlreadyDefined")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#FunctionApplicationExpressionParametersMatchAppliedFunction")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#BoundOperationMustHaveParameters")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#OperationImportEntitySetExpressionIsInvalid")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#OperationUnsupportedReturnType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#OperationOnlyInputParametersAllowedInFunctions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#IfExpressionAssertCorrectTestType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#ImmediateValueAnnotationElementAnnotationIsValid")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#ModelDuplicateSchemaElementName")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NamedElementNameIsNotAllowed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NamedElementNameMustNotBeEmptyOrWhiteSpace")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationPropertyAssociationNameIsValid")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationPropertyCorrectType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationPropertyDependentPropertiesMustBelongToDependentEntity")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationPropertyEndWithManyMultiplicityCannotHaveOperationsSpecified")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationPropertyInvalidOperationMultipleEndsInAssociatedNavigationProperties")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationPropertyPrincipalEndMultiplicity")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationPropertyWithNonRecursiveContainmentSourceMustBeFromOne")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationPropertyWithRecursiveContainmentTargetMustBeOptional")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#OpenTypesNotSupported")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#PrimitiveValueValidForType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#PropertyValueBindingValueIsCorrectType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#SchemaElementMustNotHaveKindOfNone")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#SchemaElementNamespaceIsTooLong")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#SchemaElementSystemNamespaceEncountered")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#StringTypeReferenceStringUnboundedNotValidForMaxLength")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#StructuredTypeBaseTypeMustBeSameKindAsDerivedKind")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#StructuredTypeInvalidMemberNameMatchesTypeName")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#StructuredTypePropertyNameAlreadyDefined")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#AnnotationInaccessibleTerm")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#TypeReferenceInaccessibleSchemaType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#VocabularyAnnotatableNoDuplicateAnnotations")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#VocabularyAnnotationInaccessibleTarget")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#ValueAnnotationAssertCorrectExpressionType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#TypeMustNotHaveKindOfNone")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#TypeAnnotationAssertMatchesTermType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#TemporalTypeReferencePrecisionOutOfRange")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#StructuredTypePropertiesDeclaringTypeMustBeCorrect")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#StructuredTypeInaccessibleBaseType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#StructuralPropertyNullableComplexType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#StructuralPropertyInvalidPropertyType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#StringTypeReferenceStringMaxLengthNegative")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#SchemaElementNamespaceMustNotBeEmptyOrWhiteSpace")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#SchemaElementNamespaceIsNotAllowed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#RecordExpressionPropertiesMatchType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#PropertyMustNotHaveKindOfNone")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#PrimitiveTypeMustNotHaveKindOfNone")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationPropertyWithRecursiveContainmentSourceMustBeFromZeroOrOne")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationPropertyTypeMismatchRelationshipConstraint")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationPropertyEntityMustNotIndirectlyContainItself")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationPropertyDuplicateDependentProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationPropertyDependentEndMultiplicity")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationPropertyAssociationEndNameIsValid")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NamedElementNameIsTooLong")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#ModelDuplicateEntityContainerName")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#ImmediateValueAnnotationElementAnnotationHasNameAndNamespace")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#OperationImportUnsupportedReturnTypeV1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#OperationImportParametersCannotHaveModeOfNone")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#OperationImportEntityTypeDoesNotMatchEntitySet")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#OperationImportComposableOperationImportCannotBeSideEffecting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#OperationImportCannotImportBoundOperation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#OperationParameterNameAlreadyDefinedDuplicate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#EnumMustHaveIntegerUnderlyingType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#EntityTypeKeyPropertyMustBelongToEntity")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#EntityTypeInvalidKeyNullablePart")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#EntityTypeDuplicatePropertyNameSpecifiedInEntityKey")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#EntitySetRecursiveNavigationPropertyMappingsMustPointBackToSourceEntitySet")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationPropertyMappingMustPointToValidTargetForProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationSourceInaccessibleEntityType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#EntityContainerElementMustNotHaveKindOfNone")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#ElementDirectValueAnnotationFullNameMustBeUnique")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#DecimalTypeReferenceScaleOutOfRange")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#FunctionMustHaveReturnType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#CollectionExpressionAllElementsCorrectType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#BinaryTypeReferenceBinaryMaxLengthNegative")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#OperationIsBoundOperationImportMustHaveParameters")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#OperationEntitySetPathMustBeValid")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#UnBoundFunctionOverloadsMustHaveIdenticalReturnTypes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#ModelBoundFunctionOverloadsMustHaveSameReturnType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#ModelDuplicateFunctions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#OperationReturnTypeEntityTypeMustBeValid")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#EntitySetTypeMustBeCollectionOfEntityType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#SingletonTypeMustBeEntityType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.EdmCoreModel.#Instance")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationPropertyPartnerPathShouldBeResolvable")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#NavigationPropertyBindingPathMustBeResolvable")]

// By design and already public APIs thus cannot be changed.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Date", Scope = "type", Target = "ODataToolkit.Date")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Function", Scope = "member", Target = "ODataToolkit.EdmEntityContainer.#AddFunctionImport(ODataToolkit.IEdmFunction)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Function", Scope = "member", Target = "ODataToolkit.EdmEntityContainer.#AddFunctionImport(System.String,ODataToolkit.IEdmFunction)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Function", Scope = "member", Target = "ODataToolkit.EdmEntityContainer.#AddFunctionImport(System.String,ODataToolkit.IEdmFunction,ODataToolkit.IEdmExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Function", Scope = "member", Target = "ODataToolkit.EdmEntityContainer.#AddFunctionImport(System.String,ODataToolkit.IEdmFunction,ODataToolkit.IEdmExpression,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Function", Scope = "member", Target = "ODataToolkit.IEdmFunctionImport.#Function")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Alias", Scope = "member", Target = "ODataToolkit.IEdmInclude.#Alias")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Namespace", Scope = "member", Target = "ODataToolkit.IEdmInclude.#Namespace")]

// By design and already public APIs thus cannot be changed.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Flags", Scope = "member", Target = "ODataToolkit.EdmEnumType.#.ctor(System.String,System.String,ODataToolkit.IEdmPrimitiveType,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Flags", Scope = "member", Target = "ODataToolkit.EdmEnumType.#.ctor(System.String,System.String,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Flags", Scope = "member", Target = "ODataToolkit.EdmEnumType.#.ctor(System.String,System.String,ODataToolkit.EdmPrimitiveTypeKind,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Flags", Scope = "member", Target = "ODataToolkit.IEdmEnumType.#IsFlags")]

// By design.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1065:DoNotRaiseExceptionsInUnexpectedLocations", Scope = "member", Target = "ODataToolkit.TimeOfDay.#op_Implicit(System.TimeSpan):ODataToolkit.TimeOfDay")]

// By design.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ODataToolkit.Vocabularies.EdmValue.#ODataToolkit.Vocabularies.IEdmDelayedValue.Value")]

// By design.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "ODataToolkit.Csdl.CsdlSemantics.CsdlSemanticsEntitySetReferenceExpression.#bindingContext")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "ODataToolkit.Csdl.CsdlSemantics.CsdlSemanticsEnumMemberExpression.#bindingContext")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "ODataToolkit.Csdl.CsdlSemantics.CsdlSemanticsFunctionImport.#csdlSchema")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "ODataToolkit.Csdl.CsdlSemantics.CsdlSemanticsOperationReferenceExpression.#bindingContext")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "ODataToolkit.Csdl.CsdlSemantics.CsdlSemanticsParameterReferenceExpression.#bindingContext")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "ODataToolkit.EnumHelper.#ToStringLiteral(ODataToolkit.IEdmEnumTypeReference,System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "ODataToolkit.ExtensionMethods.#SetChangeTrackingAnnotation(ODataToolkit.EdmModel,ODataToolkit.IEdmEntityContainer,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "ODataToolkit.ExtensionMethods.#SetChangeTrackingAnnotation(ODataToolkit.EdmModel,ODataToolkit.IEdmEntitySet,System.Boolean,System.Collections.Generic.IEnumerable`1<ODataToolkit.IEdmStructuralProperty>,System.Collections.Generic.IEnumerable`1<ODataToolkit.IEdmNavigationProperty>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "ODataToolkit.ExtensionMethods.#IsActionImport(ODataToolkit.IEdmOperationImport)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "ODataToolkit.ExtensionMethods.#IsFunctionImport(ODataToolkit.IEdmOperationImport)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "ODataToolkit.ExtensionMethods.#IsAction(ODataToolkit.IEdmOperation)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "ODataToolkit.ExtensionMethods.#IsFunction(ODataToolkit.IEdmOperation)")]

// Already public APIs thus cannot be changed.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1007:UseGenericsWhereAppropriate", Scope = "member", Target = "ODataToolkit.Vocabularies.TryCreateObjectInstance.#Invoke(ODataToolkit.Vocabularies.IEdmStructuredValue,System.Type,ODataToolkit.Vocabularies.EdmToClrConverter,System.Object&,System.Boolean&)")]

// By design.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration", MessageId = "0#", Scope = "member", Target = "ODataToolkit.EdmNavigationSource.#FindNavigationTarget(ODataToolkit.IEdmNavigationProperty)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "baseType2", Scope = "member", Target = "ODataToolkit.Csdl.CsdlSemantics.CsdlSemanticsComplexTypeDefinition.#ComputeBaseType()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "baseType2", Scope = "member", Target = "ODataToolkit.Csdl.CsdlSemantics.CsdlSemanticsEntityTypeDefinition.#ComputeBaseType()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "propertyValue", Scope = "member", Target = "ODataToolkit.Vocabularies.EdmStructuredValue.#.ctor(ODataToolkit.IEdmStructuredTypeReference,System.Collections.Generic.IEnumerable`1<ODataToolkit.Vocabularies.IEdmPropertyValue>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "ODataToolkit.Vocabularies.V1.CapabilitiesVocabularyModel.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "ODataToolkit.Vocabularies.V1.CoreVocabularyModel.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "ODataToolkit.Vocabularies.Community.V1.AlternateKeysVocabularyModel.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "ODataToolkit.AmbiguousOperationImportBinding.#ReturnType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "ODataToolkit.BadNavigationProperty.#DefaultValueString")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "ODataToolkit.EdmCoreModel.#FindOperationImportsByNameNonBindingParameterType(System.String,System.Collections.Generic.IEnumerable`1<System.String>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "ODataToolkit.Csdl.Parsing.Common.EdmXmlDocumentParser`1.#GetOptionalAttribute(ODataToolkit.Csdl.Parsing.Common.XmlElementInfo,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "ODataToolkit.AmbiguousLabeledExpressionBinding.#ComputeExpression()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "ODataToolkit.BadLabeledExpression.#ComputeExpression()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "ODataToolkit.Csdl.CsdlSemantics.UnresolvedEnumMember.#ComputeValue()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "ODataToolkit.Csdl.CsdlSemantics.CsdlSemanticsVocabularyAnnotation.#FindParameterizedOperationImport(System.String,System.Func`2<System.String,System.Collections.Generic.IEnumerable`1<ODataToolkit.IEdmOperationImport>>,System.Func`2<System.Collections.Generic.IEnumerable`1<ODataToolkit.IEdmOperationImport>,ODataToolkit.IEdmOperationImport>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Scope = "member", Target = "ODataToolkit.Csdl.CsdlSemantics.CsdlSemanticsModel.#WrapExpression(ODataToolkit.Csdl.Parsing.Ast.CsdlExpressionBase,ODataToolkit.IEdmEntityType,ODataToolkit.Csdl.CsdlSemantics.CsdlSemanticsSchema)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Scope = "member", Target = "ODataToolkit.Vocabularies.EdmExpressionEvaluator.#MatchesType(ODataToolkit.IEdmTypeReference,ODataToolkit.Vocabularies.IEdmValue,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Scope = "member", Target = "ODataToolkit.Csdl.Serialization.EdmModelCsdlSchemaWriter.#WriteInlineExpression(ODataToolkit.IEdmExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Scope = "member", Target = "ODataToolkit.EdmModelVisitor.#VisitExpression(ODataToolkit.IEdmExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Scope = "member", Target = "ODataToolkit.Vocabularies.EdmExpressionEvaluator.#Eval(ODataToolkit.IEdmExpression,ODataToolkit.Vocabularies.IEdmStructuredValue)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1809:AvoidExcessiveLocals", Scope = "member", Target = "ODataToolkit.Vocabularies.EdmExpressionEvaluator.#Eval(ODataToolkit.IEdmExpression,ODataToolkit.Vocabularies.IEdmStructuredValue)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1714:FlagsEnumsShouldHavePluralNames", Scope = "type", Target = "ODataToolkit.EdmTypeKind")]

// Unrecognized word: Multi
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "ODataToolkit.EdmPrimitiveTypeKind.#GeographyMultiPoint")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "ODataToolkit.EdmPrimitiveTypeKind.#GeometryMultiLineString")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "ODataToolkit.EdmPrimitiveTypeKind.#GeographyMultiPolygon")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "ODataToolkit.EdmPrimitiveTypeKind.#GeometryMultiPolygon")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "ODataToolkit.EdmPrimitiveTypeKind.#GeometryMultiPoint")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "ODataToolkit.EdmPrimitiveTypeKind.#GeographyMultiLineString")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "ODataToolkit.EdmCoreModel.#GetUntypedType()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "ODataToolkit.EdmCoreModel.#GetUntyped()")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object[])", Scope = "member", Target = "ODataToolkit.Validation.ValidationRules.#.cctor()")]
