//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyDescription("Toolkit for developing OData web services.  Can be used from Web API, Nancy, or the platform of your choice.")]
[assembly: AssemblyProduct("ODataToolkit")]
[assembly: AssemblyVersion("0.7.7150.32575")]
[assembly: AssemblyFileVersion("0.7.7150.32575")]

